name: License Check

on:
  pull_request:
    branches: [dev, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license_check:
    uses: OpenVoiceOS/gh-automations/.github/workflows/license-check.yml@dev
