name: Publish Stable Release

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  publish_stable:
    if: github.actor != 'github-actions[bot]'
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-stable.yml@dev
    secrets: inherit
    with:
      version_file: 'version.py'
      publish_pypi: true
      publish_release: true
      sync_dev: true
